spring.application.name=mr-hussle-backend
spring.datasource.url= jdbc:postgresql://localhost:5432/mr_hussle_db
spring.datasource.username= postgres
spring.datasource.password= 1756

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update